-- PostgreSQL ENUM types for MIS model
CREATE TYPE gender_type AS ENUM ('M', 'F');
CREATE TYPE locality_type AS ENUM ('URBAN', 'RURAL');
CREATE TYPE consent_type AS ENUM ('GOV_DATA_TRANSFER', 'MARKETING');
CREATE TYPE appointment_status AS ENUM ('SCHEDULED', 'CONFIRMED', 'ARRIVED', 'NO_SHOW', 'CANCELLED');
CREATE TYPE appointment_source AS ENUM ('ONLINE', 'MANUAL');
CREATE TYPE prescription_type AS ENUM ('PROCEDURE', 'MEDICATION', 'LAB_TEST', 'OTHER');
CREATE TYPE template_type AS ENUM ('STANDARD', 'CLINICAL_GUIDELINE', 'PERSONAL');
CREATE TYPE payment_method_type AS ENUM ('CASH', 'CARD', 'TRANSFER', 'OTHER');
CREATE TYPE payment_status_type AS ENUM ('PAID', 'PARTIAL', 'DEFERRED', 'NO_CASH_REGISTER');
CREATE TYPE file_type AS ENUM ('PDF', 'IMAGE', 'TEXT');
CREATE TYPE lab_order_status AS ENUM ('CREATED', 'SENT', 'IN_PROGRESS', 'COMPLETED');
CREATE TYPE lab_result_source AS ENUM ('MANUAL', 'INTEGRATION');
CREATE TYPE notification_channel AS ENUM ('SMS', 'EMAIL');
CREATE TYPE notification_type AS ENUM ('APPOINTMENT_CONFIRMATION', 'VISIT_REMINDER', 'MARKETING');
CREATE TYPE notification_status AS ENUM ('PENDING', 'SENT', 'FAILED');
CREATE TYPE integration_type AS ENUM ('SMS_PROVIDER', 'LABORATORY', 'GOV_SYSTEM');
CREATE TYPE inventory_operation_type AS ENUM ('INCOMING', 'WRITE_OFF_AUTO', 'WRITE_OFF_MANUAL');
