-- V22: Add MEDICAL_INTERVENTION and PERSONAL_DATA_PROCESSING to consent_type enum
ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'MEDICAL_INTERVENTION';
ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'PERSONAL_DATA_PROCESSING';
